name: hello-bornjre
version: "2.10"
summary: GNU Hello, the "hello world" snap
description: GNU Hello prints a friendly greeting.
grade: stable
confinement: strict

apps:
  hello:
    command: inside/runner-bj.sh
# lets change the world.
parts:
    get-tar:
        plugin: dump
        source: inside.tar.xz